# Test Gumbel softmax trick

In [8]:
import torch
import torch.nn.functional as F

In [13]:
logits_batch = torch.rand(2,4)

In [14]:
logits_batch

tensor([[0.8903, 0.0851, 0.0877, 0.9698],
        [0.8826, 0.7688, 0.6005, 0.0711]])

In [42]:
for i in range(10):
    print(F.gumbel_softmax(logits_batch, tau=1e-1, hard=True, eps=1e-10), '\n')

tensor([[0., 0., 0., 1.],
        [0., 0., 0., 1.]]) 

tensor([[0., 0., 0., 1.],
        [0., 0., 1., 0.]]) 

tensor([[0., 0., 0., 1.],
        [0., 0., 1., 0.]]) 

tensor([[1., 0., 0., 0.],
        [0., 0., 1., 0.]]) 

tensor([[0., 0., 0., 1.],
        [1., 0., 0., 0.]]) 

tensor([[1., 0., 0., 0.],
        [0., 0., 1., 0.]]) 

tensor([[1., 0., 0., 0.],
        [0., 0., 1., 0.]]) 

tensor([[1., 0., 0., 0.],
        [0., 0., 1., 0.]]) 

tensor([[0., 1., 0., 0.],
        [0., 1., 0., 0.]]) 

tensor([[0., 0., 1., 0.],
        [0., 0., 0., 1.]]) 



In [60]:
logits_batch[0,0] = 2
logits_batch[1,1] = 2

In [61]:
logits_batch

tensor([[2.0000, 0.0851, 0.0877, 0.9698],
        [0.8826, 2.0000, 0.6005, 0.0711]])

In [69]:
for i in range(10):
    print(F.gumbel_softmax(logits_batch, tau=10, hard=True, eps=1e-10), '\n')

tensor([[0., 0., 1., 0.],
        [0., 1., 0., 0.]]) 

tensor([[0., 0., 0., 1.],
        [0., 1., 0., 0.]]) 

tensor([[0., 0., 1., 0.],
        [1., 0., 0., 0.]]) 

tensor([[0., 0., 0., 1.],
        [0., 0., 0., 1.]]) 

tensor([[0., 0., 0., 1.],
        [0., 1., 0., 0.]]) 

tensor([[0., 1., 0., 0.],
        [1., 0., 0., 0.]]) 

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.]]) 

tensor([[0., 1., 0., 0.],
        [0., 1., 0., 0.]]) 

tensor([[1., 0., 0., 0.],
        [0., 0., 1., 0.]]) 

tensor([[0., 1., 0., 0.],
        [0., 0., 1., 0.]]) 



In [72]:
for i in range(10):
    print(F.gumbel_softmax(logits_batch, tau=5, hard=False, eps=1e-10), '\n')

tensor([[0.1764, 0.3665, 0.1610, 0.2961],
        [0.1431, 0.2883, 0.2027, 0.3659]]) 

tensor([[0.2561, 0.1983, 0.1751, 0.3705],
        [0.1437, 0.2956, 0.3569, 0.2038]]) 

tensor([[0.2536, 0.2148, 0.2223, 0.3093],
        [0.2021, 0.4020, 0.2335, 0.1623]]) 

tensor([[0.3385, 0.2450, 0.1511, 0.2655],
        [0.3400, 0.2450, 0.1885, 0.2265]]) 

tensor([[0.3214, 0.2519, 0.1957, 0.2310],
        [0.2897, 0.3067, 0.2036, 0.2000]]) 

tensor([[0.2807, 0.2325, 0.2630, 0.2238],
        [0.2330, 0.4279, 0.1962, 0.1428]]) 

tensor([[0.4095, 0.1412, 0.2328, 0.2166],
        [0.1730, 0.2342, 0.3916, 0.2012]]) 

tensor([[0.3874, 0.1951, 0.2081, 0.2094],
        [0.2767, 0.2416, 0.2799, 0.2018]]) 

tensor([[0.2949, 0.2566, 0.2129, 0.2356],
        [0.2818, 0.2871, 0.1796, 0.2515]]) 

tensor([[0.2576, 0.2101, 0.1794, 0.3529],
        [0.3502, 0.2182, 0.2016, 0.2300]]) 

